# Generated by Django 4.0.6 on 2022-07-16 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phoneNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
