# Generated by Django 4.0.6 on 2022-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_remove_sex_value_sex_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, unique=True, verbose_name='sex'),
        ),
    ]
