# Generated by Django 4.0.6 on 2022-07-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_alter_sex_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.ForeignKey(default='М', on_delete=django.db.models.deletion.PROTECT, to='task_app.sex'),
        ),
    ]
