# Generated by Django 4.0.6 on 2022-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_alter_user_middle_name_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='text',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
